% Author:  Jakob Nikolas Kather 

function featureVector = histogramLower(imgInGray)
    % histogram-based features: central moment 1 to 5
    % input: grayscale image, values 0...1 (double precision floats)
    % compute histogram descriptors
    featureVector = [ mean(imgInGray(:)),...
                      var(imgInGray(:)),...
                      skewness(imgInGray(:)),...
                      kurtosis(imgInGray(:)),...
                      moment(imgInGray(:),5)];
end